version: "3.5"
services:
    api:
        container_name: "kidsapi"
        build:
            context: ./app
        ports:
            - "8000:8000"
        restart: always
        volumes:
            - ./app/:/usr/src/app/